name: Test

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools first
      run: pip3 install setuptools

    - name: Install XVFB
      run: sudo apt-get install -y xvfb

    - name: Install dependencies (Python)
      run: make update

    - name: Install dependencies (JS)
      run: sudo npm install -g jshint

    - name: Lint
      run: make lint radon

    - name: Test
      run: make test test_system

    - name: Docs
      run: make docs

    - name: Build package
      run: make build
