name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]  # TODO test on 3.8 as well

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install setuptools first
      run: pip3 install setuptools

    - name: Install dependencies
      run: make update

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    # TODO run system tests
